settings:
  name: Amazon FSx for ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Amazon FSx for ONTAP docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about FSx for ONTAP
          url: /start/concept-fsx-aws.html
        - title: Quick start
          url: /start/task-getting-started-fsx.html
        - title: Set up permissions for FSx for ONTAP
          url: /requirements/task-setting-up-permissions-fsx.html
        - title: Security group rules for FSx for ONTAP
          url: /requirements/reference-security-groups-fsx.html
    - title: Use Amazon FSx for ONTAP
      entries:
        - title: Create and manage a working environment
          url: /use/task-creating-fsx-working-environment.html
        - title: Create and mount volumes
          url: /use/task-add-fsx-volumes.html
        - title: Manage volumes and data services
          url: /use/task-manage-fsx-volumes.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support/task-support-registration.html
        - title: Get help
          url: /support/task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
    name: Cloud Manager
    repo: cloud-manager-family
    sidebar_label: All Cloud Manager documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Release notes
          url: /whats-new.html
        - title: Learn about Amazon FSx for ONTAP
          url: /start/concept-fsx-aws.html
        - title: Quick start
          url: /start/task-getting-started-fsx.html
        - title: Set up permissions
          url: /requirements/task-setting-up-permissions-fsx.html
        - title: Security group rules 
          url: /requirements/reference-security-groups-fsx.html
    - title: Use Amazon FSx for ONTAP
      links:
        - title: Create and manage the working environment
          url: /use/task-creating-fsx-working-environment.html
        - title: Create and mount volumes
          url: /use/task-add-fsx-volumes.html
        - title: Manage volumes and data services
          url: /use/task-manage-fsx-volumes.html
    - title: Knowledge and support
      links:
        - title: Register for support
          url: /support/task-support-registration.html
        - title: Get help
          url: /support/task-get-help.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
