settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Amazon FSx for NetApp ONTAP docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Amazon FSx for NetApp ONTAP
          url: /start/concept-fsx-aws.html
        - title: Quick start
          url: /start/task-getting-started-fsx.html
    - title: Requirements
      entries:
        - title: Set up permissions
          url: /requirements/task-setting-up-permissions-fsx.html
        - title: Security group rules
          url: /requirements/reference-security-groups-fsx.html
    - title: Use Amazon FSx for NetApp ONTAP
      entries:
        - title: Create or discover a working environment
          url: /use/task-creating-fsx-working-environment.html
        - title: Manage a working environment
          url: /use/task-manage-working-environment.html
        - title: Create and mount a volume
          url: /use/task-add-fsx-volumes.html
        - title: Manage volumes
          url: /use/task-manage-fsx-volumes.html
        - title: Add and manage a storage VM
          url: /use/task-add-fsx-svm.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support/task-support-registration.html
        - title: Get help
          url: /support/task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
    name: BlueXP
    repo: bluexp-family