settings:
  name: "Product Name"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Amazon FSx for ONTAP docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about FSx for ONTAP
          url: /concept-fsx-aws.html
        - title: Quick start
          url: /task-getting-started-fsx.html
        - title: Set up permissions for FSx for ONTAP
          url: /task-setting-up-permissions-fsx.html
    - title: Use Amazon FSx for ONTAP
      entries:
        - title: Create and manage a working environment
          url: /task-creating-fsx-working-environment.html
        - title: Create and manage volumes
          url: /task-manage-fsx-volumes.html
    - title: Knowledge and support
      url: /get-help.html
    - title: Legal notices
      url: /legal-notices.html
