settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Amazon FSx for NetApp ONTAP docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Amazon FSx for NetApp ONTAP
          url: /start/concept-fsx-aws.html
        - title: Quick start
          url: /start/task-getting-started-fsx.html
        - title: Set up permissions
          url: /requirements/task-setting-up-permissions-fsx.html
        - title: Create or discover a working environment
          url: /use/task-creating-fsx-working-environment.html
    - title: Manage an FSx for ONTAP file system
      url: /use/task-manage-working-environment.html
    - title: Remove an FSx for ONTAP file system from a workspace
      url: /use/task-remove-fsx-working-environment.html  
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support/task-support-registration.html
        - title: Get help
          url: /support/task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
    name: BlueXP
    repo: bluexp-family