settings:
  name: "Amazon FSx for ONTAP"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Amazon FSx for ONTAP docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about FSx for ONTAP
          url: /concept-fsx-aws.html
        - title: Quick start
          url: /task/task-getting-started-fsx.html
        - title: Set up permissions for FSx for ONTAP
          url: /task/task-setting-up-permissions-fsx.html
        - title: Security group rules for FSx for ONTAP
          url: /reference/reference_security_groups_fsx.html
    - title: Use Amazon FSx for ONTAP
      entries:
        - title: Create and manage a working environment
          url: /task/task-creating-fsx-working-environment.html
        - title: Create and mount volumes
          url: /task/task-add-fsx-volumes.html
        - title: Manage volumes and data services
          url: /task/task-manage-fsx-volumes.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task/task-support-registration.html
        - title: Get help
          url: /task/task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
homepage:
  tiles:
    - title: Get started with Amazon FSx for ONTAP
      links:
        - title: What's new
          url: whats-new.html
        - title: Learn about Amazon FSx for ONTAP
          url: /concept-fsx-aws.html
        - title: Quick start
          url: /task/task-getting-started.html
        - title: Security group rules for FSx for ONTAP
          url: /reference_security_groups_fsx.html
    - title: Create a working environment
      links:
        - title: Set up permissions
          url: /task/task-setting-up-permissions.html
        - title: Create a working environment
          url: /task/task-creating-fsx-working-environment.html
    - title: Create and manage volumes
      links:
        - title: Create volumes
          url: /task/task-add-fsx-volumes.html
        - title: Manae volumes
          url: /task/task-manage-fsx-volumes.html
    - title: Knowledge and support
      links:
        - title: Register for support
          url: /task/task-support-registration.html
        - title: Get help
          url: /task/task-get-help.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
