=== Tracker response support

Tracker now provides API responses so that you can see the REST API output related to the task.

=== Link authentication support for AWS Secrets Manager

You now have the option to use secrets from AWS Secrets Manager to authenticate links so that you don't have to use credentials stored in BlueXP Workloads.

=== Implement best practices for an FSx for ONTAP file system
BlueXP workload factory provides a dashboard where you can review the well-architected status of your file system configurations. You'll find the total well-architected score. File system configuration analysis includes the five pillars according the AWS Well-Architected Framework: reliability, security, operational excellence, cost optimization, and performance efficiency. You can leverage this analysis to implement best practices for your FSx for ONTAP file systems.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html[Learn about the well-architected analysis for file system configurations^]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html[Implement best practices for your file systems^]

==== Well-architected notifications in the canvas
FSx for ONTAP file systems with well-architected issues now display a notification in the Canvas indicating when file systems have issues to fix.  