---
sidebar: sidebar
permalink: use/task-manage-fsx-volumes.html
keywords: fsx for ontap, fsx, aws, delete volumes, delete nfs volumes, delete cifs volumes, tiering policy, mount path, get mount path, mount volume, delete volumes, snapshots, edit volume, clone volume, clone
summary: You can manage volumes, clones, and snapshots, and change tiering policies for FSx for ONTAP using BlueXP.
---

= Manage volumes for FSx for ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can view and manage volumes, clones, and snapshots, and change tiering policies for FSx for ONTAP using BlueXP.

== View volume details
After you create a volume, you can view the configuration details. 

. Open the working environment.
+
NOTE: You can hover over the volume name to display the volume type.

. Open the volume tab and select *Manage Volume* to open the *Volume Actions* menu.
. Select *View volume details*.

== Edit volumes

After you create a volume, you can modify it at any time.

.Steps

. Open the working environment.
. Open the volume tab and select *Manage Volume* to open the *Volume Actions* menu.
. Select *Edit volume settings*.
. Select *Apply*.

== Clone volumes

After you create a volume, you can create a new read-write volume from a new Snapshot.

.Steps

. Open the working environment.

. Open the volume tab and select *Manage Volume* to open the *Volume Actions* menu.

. Select *Clone the volume*.

. Enter a name for the cloned volume.

. Select *Clone*.

== Manage volume tags
You can add, modify, or delete volume tags. Tags added in BlueXP are reflected in the AWS Management Console. It can take up to an hour to synchronize tags with the AWS Management Console.

NOTE: You cannot edit volume tags you created in BlueXP until they sync with AWS. This can take up to an hour. If the *Manage volume tags* option is grayed out, AWS has not yet synced the volume tags. 

.Steps

. Open the working environment.

. Open the volume tab and select *Manage Volume* to open the *Volume Actions* menu.

. Select *Manage volume tags*.

. Select *Save* to apply your changes. 

== Manage Snapshot copies

Snapshot copies provide a point-in-time copy of your volume. Create Snapshot copies and restore the data to a new volume.

.Steps

. Open the working environment.

. Open the volume tab and select *Manage Volume* to open the *Protection Actions* menu.

. Select one of the available options to manage Snapshot copies:

* *Create a Snapshot copy*
* *Restore from a Snapshot copy*

. Follow the prompts to complete the selected action.

== Change the tiering policy

Change the tiering policy for the volume.

.Steps

. Open the working environment.

. Open the volume tab and select *Manage Volume* to open the *Advanced Actions* menu.

. Select *Change Tiering policy*.

. Select a new volume tiering policy and click *Change*.

== Delete volumes

Delete the volumes that you no longer need.

.Before you begin

You cannot delete a volume that was previously part of a SnapMirror relationship using BlueXP. SnapMirror volumes must be deleted using the AWS Management Console or CLI.

.Steps

. Open the working environment.

. Open the volume tab and select *Manage Volume* to open the *Volume Actions* menu.

. Select *Delete the volume*.

. Enter the working environment name and confirm that you want to delete the volume. It can take up to an hour before the volume is completely removed from BlueXP.

NOTE: If you try to delete a cloned volume, you will receive an error.
