---
sidebar: sidebar
permalink: start/concept-fsx-aws.html
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager
summary: Amazon FSx for NetApp ONTAP is a fully managed service allowing customers to launch and run file systems powered by NetApp’s ONTAP storage operating system. FSx for ONTAP provides the same features, performance, and administrative capabilities NetApp customers use on premises today, with the simplicity, agility, security, and scalability of a native AWS service.
---

= Learn about Amazon FSx for NetApp ONTAP 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[Amazon FSx for NetApp ONTAP^] is a fully managed service allowing customers to launch and run file systems powered by NetApp’s ONTAP storage operating system. FSx for ONTAP provides the same features, performance, and administrative capabilities NetApp customers use on premises, with the simplicity, agility, security, and scalability of a native AWS service.

== Features

* No need to configure or manage storage devices, software, or backups.
* Support for CIFS, NFSv3, NFSv4.x, and SMB v2.0 - v3.1.1 protocols.
* Low cost, virtually unlimited data storage capacity using available Infrequently Accessed (IA) storage tier.
* Certified to run on latency-sensitive applications including Oracle RAC.
* Choice of bundled and pay-as-you-go pricing.

== Additional features in BlueXP

* Using link:https://docs.netapp.com/us-en/cloud-manager-family/[BlueXP^] (formerly Cloud Manager) and a Connector in AWS, you can create and manage volumes, replicate data, and integrate FSx for ONTAP with NetApp cloud services, such as Data Sense and Cloud Sync.

* Using Artificial Intelligence (AI) driven technology, Cloud Data Sense can help you understand data context and identify sensitive data that resides in your FSx for ONTAP accounts. https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html[Learn more^].

* Using NetApp Cloud Sync, you can automate data migration to any target in the cloud or on premises. https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html[Learn more^]

== Cost

Your FSx for ONTAP account is maintained by AWS and not by BlueXP. Refer to https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[Amazon FSx for NetApp ONTAP getting started guide^].

There is an additional cost associated with using the Connector in AWS and the optional data services such as Cloud Sync and Data Sense.

== Supported regions

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/[View supported Amazon regions.^]

== Getting help

Amazon FSx for NetApp ONTAP is an AWS first-party solution. For questions or technical support issues associated with your Amazon FSx for NetApp ONTAP file system, infrastructure, or any solution using this service, use the Support Center in your AWS console to open a support case with AWS. Select the “FSx for ONTAP” service and appropriate category. Provide the remaining information required to create your AWS support case.

For general questions about BlueXP or BlueXP storage solutions and services, you can start with the in-line BlueXP chat.

For technical support issues specific to BlueXP or BlueXP storage solutions and services,  you can open a NetApp support ticket using your BlueXP account level serial number. You will need to link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/support/task-support-registration.html[register your BlueXP account^] to activate support.